#!/usr/bin/env bash
#
# watch-push.sh — watch a folder and push every new markdown file to a project's
# context layer as a note, using `px context apply`.
#
# Each note-*.md in the folder becomes one project-scoped context note whose TEXT
# is the file content. `px context apply` is idempotent, so each tick only pushes
# files that are new or changed. Files are never deleted.
#
# The context layer attaches notes to an EXISTING project, so you must give it a
# project id (context notes have nowhere to live otherwise). Create a project
# first — in the app, or by running one of the other examples — and pass its id:
#
#   ONTOLOGY_ID=<project id> JARVISPY_URL=... PMTX_TOKEN=... ./watch-push.sh
#
# On first run it scaffolds ./workspace pointing at that project. Ctrl-C to stop.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
WS="${WORKSPACE:-$HERE/workspace}"
INTERVAL="${1:-5}"
PX="${PX:-px}"
PROJ="$WS/projects/ctx"
VAULT="$PROJ/context"
MANIFEST="$VAULT/notes.context.md"

: "${JARVISPY_URL:?set JARVISPY_URL, e.g. https://api.prometheux.ai/jarvispy/<org>/<user>}"
: "${PMTX_TOKEN:?set PMTX_TOKEN (your account JWT)}"
export JARVISPY_URL PMTX_TOKEN
command -v "$PX" >/dev/null 2>&1 || { echo "FATAL: '$PX' not found on PATH (set PX=...)." >&2; exit 2; }

# Scaffold the workspace on first run (needs ONTOLOGY_ID to know where to push).
if [[ ! -f "$PROJ/prometheux.yaml" ]]; then
  : "${ONTOLOGY_ID:?first run: set ONTOLOGY_ID to the project id these notes should attach to}"
  mkdir -p "$PROJ/concepts" "$VAULT"
  cat > "$WS/prometheux.workspace.yaml" <<'YAML'
schemaVersion: 1
workspace:
  name: continuous-context-example
projects:
  - ./projects/ctx
YAML
  cat > "$PROJ/prometheux.yaml" <<YAML
schemaVersion: 1
project:
  id: ${ONTOLOGY_ID}
  name: Continuous Context Example
  scope: user
concepts: ./concepts
context: ./context
YAML
  echo "Scaffolded $WS → pushing context notes to project ${ONTOLOGY_ID}."
fi
mkdir -p "$VAULT"

echo "Watching $VAULT every ${INTERVAL}s (Ctrl-C to stop)."
echo

# Rebuild the *.context.md manifest to reference every note-*.md in the folder.
# scope: project → notes attach to this project's id (from prometheux.yaml).
regen_manifest() {
  local entries=() f
  for f in "$VAULT"/note-*.md; do
    [[ -e "$f" ]] || continue
    entries+=("  - $(basename "$f")")
  done
  {
    echo "---"
    echo "scope: project"
    echo "activation: retrieved"
    echo "kind: fact"
    if [[ ${#entries[@]} -eq 0 ]]; then
      echo "notes: []"
    else
      echo "notes:"
      printf '%s\n' "${entries[@]}"
    fi
    echo "---"
    echo "Auto-generated by watch-push.sh — one note per note-*.md in this folder."
  } > "$MANIFEST"
}

last=""
while true; do
  cur="$(ls -1 "$VAULT"/note-*.md 2>/dev/null | sort || true)"
  if [[ "$cur" != "$last" ]]; then
    regen_manifest
    echo "[$(date +%H:%M:%S)] folder changed → px context apply"
    if "$PX" context apply "$WS" -y; then
      last="$cur"
    else
      echo "  (apply failed — will retry next tick)"
    fi
    echo
  fi
  sleep "$INTERVAL"
done
